spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver

  datasource:
    url: jdbc:postgresql://localhost:5432/dater?socketTimeout=30
    username: dater
    password: dater
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
