spring:
  #  datasource:
  #    url: jdbc:h2:mem:mydb
  #    username: sa
  #    password: password
  #    driverClassName: org.h2.Driver

  datasource:
    url: jdbc:postgresql://localhost:5432/dater?socketTimeout=30
    username: dater
    password: dater
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: dater
  #  jpa:
  #    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB


jwt:
  signing-key: "secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey"