spring:
  #  datasource:
  #    url: jdbc:h2:mem:mydb
  #    username: sa
  #    password: password
  #    driverClassName: org.h2.Driver
  profiles:
    active:
      - local

  datasource:
    url: jdbc:postgresql://localhost:5432/dater?socketTimeout=30
    username: dater
    password: dater
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: dater
  #  jpa:
  #    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          public-key-location: classpath:my-test-key.pub

springdoc:
  swagger-ui:
    path: "/swagger-ui"

logging:
  level:
    #    web: debug
    org:
      springframework:
        security: TRACE

openapi:
  dev-url: http://localhost:8080
  prod-url: https://dater-api.com

jwt:
  signing-key: "secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey"