spring:
  profiles:
    active:
      - local

  datasource:
    url: jdbc:postgresql://localhost:5432/dater?socketTimeout=30
    username: dater
    password: dater
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: dater

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: "/swagger-ui"

logging:
  level:
    #    web: debug
    org:
      springframework:
        security: TRACE

openapi:
  dev-url: http://localhost:8080
  prod-url: https://dater-api.com

jwt:
  signing-key: "secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey"