spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: create

jwt:
  signing-key: "secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey"